# These are supported funding model platforms

github: mrgogo7 # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
custom: ['https://www.patreon.com/mRGogo7', 'https://www.buymeacoffee.com/mrgogo'] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
